# Generated by Django 6.1.1 on 2026-09-29 08:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='maternilink_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='maternilink_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('doctor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('clinic_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalOrderRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_msgs', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_msgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotherProfile',
            fields=[
                ('mother_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(max_length=5)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mother_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scheduled_datetime', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.doctorprofile')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.motherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyProfile',
            fields=[
                ('pregnancy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lmp_date', models.DateField()),
                ('edd_date', models.DateField()),
                ('pregnancy_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.doctorprofile')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.motherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_url', models.URLField(max_length=500)),
                ('record_type', models.CharField(max_length=100)),
                ('summary_notes', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.medicalorderrequest')),
                ('uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.pregnancyprofile')),
            ],
        ),
        migrations.AddField(
            model_name='medicalorderrequest',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.pregnancyprofile'),
        ),
        migrations.CreateModel(
            name='MaternalHealthLog',
            fields=[
                ('maternal_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('systolic_bp', models.IntegerField()),
                ('diastolic_bp', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.pregnancyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KickCountLog',
            fields=[
                ('kick_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('kick_count', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.pregnancyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FetalHealthLog',
            fields=[
                ('fetal_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fetal_heart_rate_bpm', models.IntegerField()),
                ('fundal_height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gestational_age_weeks', models.IntegerField()),
                ('recorded_date', models.DateField()),
                ('recorded_by_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.doctorprofile')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.pregnancyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subjective_notes', models.TextField()),
                ('objective_findings', models.TextField()),
                ('assessment', models.TextField()),
                ('clinical_plan', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.doctorprofile')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.pregnancyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('prescribed_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.doctorprofile')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.pregnancyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('reminder_type', models.CharField(max_length=100)),
                ('scheduled_time', models.TimeField()),
                ('frequency', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.motherprofile')),
            ],
        ),
    ]
